calendar_id: EUR_DERIV
description: Eurex and TARGET2 settlement calendar
weekend: [SATURDAY, SUNDAY]
holidays:
  - {date: "2026-01-01", name: New Year's Day}
  - {date: "2026-04-03", name: Good Friday}
  - {date: "2026-04-06", name: Easter Monday}
  - {date: "2026-05-01", name: Labour Day}
  - {date: "2026-12-25", name: Christmas Day}
  - {date: "2026-12-26", name: St Stephen's Day}
