#!/usr/bin/env python3
"""Generate one task context pack per task in the execution plan.

Kept as a committed script rather than hand-written markdown so that a plan
amendment regenerates every pack consistently. Run: python3 scripts/gen_task_packs.py
"""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "docs" / "tasks"

# id: (title, milestone, depends, scope, objective, [acceptance], validate, refs)
T = {
"T-001": ("Repo scaffold", "G", "-", "root",
 "Create the directory tree from LLD §1, a Makefile skeleton with empty targets, .gitignore, LICENSE and a placeholder README.",
 ["Tree matches LLD §1 exactly, including empty dirs with .gitkeep",
  "`make` with no arguments prints the target list",
  "No language toolchain files yet beyond placeholders"],
 "make", "03-lld.md §1"),
"T-002": ("Go module and lint harness", "G", "T-001", "go/",
 "Initialise a single Go module with three cmd packages, wire golangci-lint, go vet and go test.",
 ["`go build ./...` succeeds with stub mains",
  "golangci-lint config committed and passing",
  "One trivial table-driven test exists and runs"],
 "cd go && go build ./... && go vet ./... && golangci-lint run && go test ./...",
 "03-lld.md §1"),
"T-003": ("Python project and lint harness", "G", "T-001", "python/",
 "Initialise the Python project with uv, pyproject, ruff, mypy strict and pytest.",
 ["`uv sync` resolves offline from a committed lock",
  "ruff and mypy pass on a stub module",
  "One trivial parametrised pytest runs"],
 "cd python && uv run ruff check . && uv run mypy src && uv run pytest",
 "03-lld.md §1"),
"T-004": ("Protobuf contracts and codegen", "G", "T-002, T-003", "proto/, buf.*, go/gen/, python/src/hmv1/",
 "Author every message in LLD §2 as proto3, configure buf, generate Go and Python types, and add a codegen-freshness check that fails if generated code is stale.",
 ["Every message and enum in LLD §2 present with the exact field numbers",
  "buf lint and buf breaking pass",
  "Regenerating produces no diff; a deliberate stale edit fails the check",
  "Round-trip test: Go marshals protojson, Python unmarshals, fields equal"],
 "buf lint && buf generate && git diff --exit-code",
 "03-lld.md §2 (frozen)"),
"T-005": ("Compose core profile", "G", "T-001", "docker-compose.yml, */Dockerfile",
 "Compose file with redpanda, postgres and the six service containers, each with a healthcheck and a dependency ordering.",
 ["`docker compose up` reaches healthy for all services",
  "Cold start under 60 seconds on a developer machine",
  "Topics from HLD §4.1 auto-created on boot with the stated partition keys",
  "No Node, no JVM, no metrics stack (ADR-012, ADR-014)"],
 "docker compose up -d --wait && docker compose ps",
 "02-hld.md §4.1, ADR-008"),
"T-006": ("make check and CI", "G", "T-002..T-005", "Makefile, .github/",
 "Aggregate every static and test gate behind one command, and run the identical command in GitHub Actions.",
 ["`make check` runs fmt, lint, type check, buf lint, codegen freshness, all unit tests",
  "Runs fully offline with no network and no API key",
  "CI workflow invokes `make check` verbatim, not a reimplementation"],
 "make check", "03-lld.md §9"),
"T-007": ("Postgres migrations", "G", "T-005", "go/internal/store/migrations/",
 "Implement the DDL from LLD §6 as ordered, idempotent migrations with an embedded runner.",
 ["All five tables plus indexes created",
  "Migrations are idempotent and re-runnable",
  "A rollback path exists for each migration"],
 "make migrate && make check", "03-lld.md §6"),
"T-008": ("Bus wrappers", "G", "T-004", "go/internal/bus/, python/src/inspector/bus.py",
 "Thin producer/consumer wrappers in both languages: protojson encoding, manual offset commit, bounded in-flight work, correlation-id propagation.",
 ["Publish and consume round-trip verified in both languages against a live broker",
  "Offsets commit only after successful downstream publish",
  "Consumer honours context cancellation and shuts down cleanly"],
 "make check && make test-bus", "02-hld.md §4.1, §8"),
"T-009": ("Structured logging and masking hook", "G", "T-002, T-003", "go/internal/masking/, go/internal/logging/, python/src/inspector/logging.py",
 "JSON logging with correlation IDs in both languages, and a serialisation hook that masks account numbers to last-4 while leaving account names intact.",
 ["Masking applied at serialisation, never at call sites",
  "Account name survives unmasked; account number renders as ****0119",
  "Property test: no log line in the suite contains a full account number",
  "HM_MASK_ACCOUNTS=false disables it for local debugging only"],
 "make check", "ADR-011, 03-lld.md §10"),
"T-010": ("Portwatch minimal", "M0", "T-008", "go/cmd/portwatch/, go/internal/ingress/",
 "Watch a directory, hash new files, store the raw payload, publish ArrivalRaw. No stability logic yet.",
 ["A file dropped into the landing dir produces exactly one ArrivalRaw",
  "content_sha256 matches sha256sum of the file",
  "Raw payload readable back from the object store by URI"],
 "make check && make test-e2e-portwatch", "03-lld.md §2.2, §5.1"),
"T-011": ("Inspector minimal", "M0", "T-008", "python/src/inspector/",
 "Consume ArrivalRaw, sniff CSV, parse, apply Tier 1 alias mapping only, write canonical Parquet, publish ArrivalClassified.",
 ["A well-formed CSV trade file maps at least 10 columns via Tier 1",
  "Parquet output matches the LLD §3 schema with decimal types, not floats",
  "Every FieldMapping carries a tier and confidence; none are blank"],
 "make check", "03-lld.md §2.3, §3"),
"T-012": ("Berthmaster minimal", "M0", "T-007, T-008", "go/cmd/berthmaster/, go/internal/slot/",
 "Open a slot on first arrival, move to PARTIAL, emit BerthAssigned when both sides present. No late window or supersession yet.",
 ["Slot key is (client, domain, value_date)",
  "State transition and audit write happen in one transaction",
  "BerthAssigned published exactly once per completed slot"],
 "make check", "03-lld.md §5.5, §2.6"),
"T-013": ("Recon stub", "M0", "T-008", "python/src/reconstub/",
 "Consume BerthAssigned, load both Parquet sides, emit a deliberately naive break report to disk and log.",
 ["Reads both sides by URI from the assignment",
  "Writes a break report naming the client, domain and value date",
  "Contains no intelligence whatsoever; that is the point"],
 "make check", "01-requirements.md §2"),
"T-014": ("M0 end-to-end test", "M0", "T-010..T-013", "tests/integration/",
 "Drive the full Compose stack: drop one CSV, assert a break report appears with the right client and value date.",
 ["Test starts the stack, seeds one file, polls for the report, tears down",
  "Fails loudly if any service is unhealthy",
  "Runs in under two minutes"],
 "make test-e2e", "04-execution-plan.md §5"),
"T-015": ("Write-completion detection", "M1", "T-010", "go/internal/arrival/",
 "Emit only when a file is fully written: quiet window on size and mtime across two polls, or sentinel present. Rescan and reconcile on restart.",
 ["A file written in slow chunks emits once, after completion, never mid-write",
  "Sentinel short-circuits the quiet window",
  "Kill and restart mid-write produces no duplicate and no loss"],
 "make check && make test-stability", "03-lld.md §5.1, FR-2"),
"T-016": ("Dedupe and suppression", "M1", "T-015, T-007", "go/internal/arrival/, go/internal/store/",
 "Content-hash dedupe store. Identical content under a different filename is a redelivery, not a new arrival.",
 ["Exact duplicate suppressed, no ArrivalRaw published",
  "Suppression written to the audit topic referencing the original arrival_id",
  "Different filename, same content still suppressed (FR-7)",
  "Board can show a seen-count rather than silently discarding"],
 "make check", "FR-6, FR-7, HLD §5.5"),
"T-017": ("JSON queue ingress", "M1", "T-015", "go/internal/ingress/",
 "Second ingress path: consume JSON payloads from an upstream queue and emit ArrivalRaw with ingress=QUEUE.",
 ["Queue payload stored to the object store and hashed identically to a file",
  "Dedupe applies across both ingress paths",
  "Malformed payload dead-lettered, not crashed on"],
 "make check", "FR-3"),
"T-018": ("Object store abstraction", "M1", "T-002", "go/internal/store/objectstore/",
 "ObjectStore interface with an fs adapter (default) and an s3 adapter, implemented and unit-tested but not wired into the demo.",
 ["Interface covers put, get, stat, uri round-trip",
  "fs adapter used by default via HM_OBJECT_STORE=fs",
  "s3 adapter unit-tested against a fake; no MinIO container"],
 "make check", "ADR-015"),
"T-019": ("Excel parser", "M2", "T-011", "python/src/inspector/parsers/",
 "Parse xlsx to ParsedTable: detect the header row, handle merged cells, skip trailing totals rows, pick the right sheet.",
 ["Header detected when preceded by title and blank rows",
  "Merged header cells forward-filled correctly",
  "A trailing 'Total' row is excluded from row_count",
  "Multi-sheet workbook selects the data sheet, not the cover sheet"],
 "make check", "R-4, 03-lld.md §5.2"),
"T-020": ("XML parser", "M2", "T-011", "python/src/inspector/parsers/",
 "Generic XML to ParsedTable via repeating-element detection and path flattening; source_field is the XPath.",
 ["Repeating record element detected without configuration",
  "Nested elements flattened to dotted paths",
  "Attributes captured alongside elements"],
 "make check", "FR-22"),
"T-021": ("FIXML parser", "M2", "T-020", "python/src/inspector/parsers/",
 "FIXML documents to ParsedTable, including repeating groups and standard tag semantics.",
 ["Execution report elements mapped to rows",
  "Repeating groups flattened without collision",
  "Tag names preserved as source_field for provenance",
  "No FIX session logic; files only"],
 "make check", "FR-22, out-of-scope §7"),
"T-022": ("Email text parser", "M2", "T-011", "python/src/inspector/parsers/",
 "Extract structured records from a free-text email body describing cash or collateral movements.",
 ["Amounts, currencies, dates and account references extracted with positions retained",
  "Multiple movements in one body produce multiple rows",
  "Low extraction confidence propagates rather than being hidden"],
 "make check", "FR-22, corpus case 9"),
"T-023": ("JSON payload parser", "M2", "T-011", "python/src/inspector/parsers/",
 "Parse queue JSON payloads, including nested and array-of-record shapes.",
 ["Array-of-objects and single-object shapes both handled",
  "Nested objects flattened to dotted source_field paths",
  "Type information preserved into the canonical decimals"],
 "make check", "FR-3"),
"T-024": ("Content-based format sniffing", "M2", "T-019..T-023", "python/src/inspector/sniff.py",
 "Decide format from content, never extension. Each parser reports a sniff confidence; highest wins.",
 ["A CSV named .txt is detected as CSV",
  "A FIXML file named .xml is detected as FIXML, not generic XML",
  "An xlsx renamed .csv is detected as EXCEL by magic bytes",
  "Ambiguity below threshold routes to quarantine, not a guess"],
 "make check", "FR-17"),
"T-025": ("Client registry and calendars", "M3", "T-002", "go/internal/registry/, config/",
 "Load and validate per-client YAML per LLD §4, plus business calendars. Unknown keys are errors. Hot reload.",
 ["Six example client configs across five venues committed",
  "Invalid config fails at load with a path pointer to the offending key",
  "cuts_per_day honoured (FR-10)",
  "Calendars cover weekends and venue holidays"],
 "make check", "03-lld.md §4, FR-33"),
"T-026": ("Client attribution", "M3", "T-025", "python/src/inspector/attribution.py",
 "Identify the owning client from filename patterns, embedded account identifiers and source hints, with a calibrated confidence.",
 ["Filename regex hints from client config applied",
  "Account IDs found in content validated against the registry",
  "Conflicting evidence lowers confidence rather than picking arbitrarily",
  "Unattributable file scores below the quarantine threshold"],
 "make check", "FR-18, FR-19"),
"T-027": ("Value-date resolution", "M3", "T-025", "python/src/inspector/valuedate.py",
 "Three-source resolution with content precedence, calendar validation and mismatch flagging, per LLD §5.4.",
 ["Content-explicit single value resolves at 0.97 confidence",
  "Filename/content disagreement always sets mismatch_flagged (FR-12)",
  "Resolved date is always a business day on the client calendar",
  "Property test: resolver never returns a weekend or holiday"],
 "make check", "03-lld.md §5.4, FR-11..FR-14"),
"T-028": ("Canonical schema and Tier 1 dictionary", "M3", "T-011", "python/src/inspector/mapping/",
 "Freeze the canonical record and build the alias dictionary covering real venue and custody vocabulary.",
 ["Header normalisation strips case, spaces, punctuation and unit suffixes",
  "Dictionary covers ICE, CME, CBOE, LSEG, EUREX, NYSE, HKEX and Nasdaq conventions",
  "field_overrides from client config take precedence over the global dictionary",
  "No canonical field can be assigned twice in one mapping"],
 "make check", "03-lld.md §3, ADR-004"),
"T-029": ("Tier 2 local matching", "M3", "T-028", "python/src/inspector/mapping/",
 "Rapidfuzz token-set scoring plus fastembed MiniLM cosine similarity against canonical field descriptions, with a fuzzy-only degraded mode.",
 ["Escalation only for headers Tier 1 missed",
  "Combined score thresholded; below threshold escalates rather than guessing",
  "Model absent falls back to fuzzy-only and records the degradation",
  "Evidence string records the matched candidate and score"],
 "make check", "ADR-013, ADR-004"),
"T-030": ("Tier 3 seam and template cache", "M3", "T-029", "python/src/inspector/mapping/",
 "MappingAdjudicator protocol, DeterministicFake, and a template-fingerprint cache in Postgres. No live API calls in this task.",
 ["Fingerprint is an ordered hash of the header set plus client",
  "Second file with the same layout costs zero adjudications",
  "Fake is bound by default so the whole suite runs offline (NFR-12)",
  "Confirmed decisions promotable into client field_overrides (FR-28)"],
 "make check", "03-lld.md §5.2, ADR-004"),
"T-031": ("Price disambiguation", "M3", "T-028", "python/src/inspector/mapping/prices.py",
 "All four steps from LLD §5.3: vocabulary, overrides, structural constancy, amount cross-check.",
 ["A file with four price columns resolves trade and settlement correctly",
  "A bare column named only 'Price' resolved by structural evidence",
  "quantity x candidate ~ net_amount used as the tie-break",
  "Unresolvable ambiguity quarantines rather than guessing (FR-25)"],
 "make check", "03-lld.md §5.3, FR-25, FR-26"),
"T-032": ("Confidence and disposition", "M3", "T-026, T-027, T-030, T-031", "python/src/inspector/confidence.py",
 "Weighted composition per LLD §5.6 and routing to dispatch, quarantine or reject.",
 ["Weights: material fields 3, identifiers 2, others 1",
  "Thresholds 0.85 / 0.60 configurable by env",
  "Disposition recorded on the classified message and in audit",
  "Quarantine reasons are specific, never 'low confidence'"],
 "make check", "03-lld.md §5.6, FR-29, FR-30"),
"T-033": ("Full slot state machine", "M4", "T-012, T-025", "go/internal/slot/",
 "Complete the state machine with the T+/-2 late window, per-client overrides and deadline tracking.",
 ["Arrival within +/-2 business days binds to the correct historical slot (FR-14, FR-15)",
  "Deadline computed on the client calendar, not naive dates",
  "Late window overridable per client",
  "State transitions exhaustively unit-tested including illegal transitions"],
 "make check", "ADR-010, 03-lld.md §5.5"),
"T-034": ("Supersession", "M4", "T-033", "go/internal/slot/",
 "Correction handling: emit BerthSuperseded then a replacement BerthAssigned, strictly ordered on the same partition.",
 ["Same client/domain/value_date with a new hash supersedes",
  "Void always observed before replacement by every consumer",
  "cuts_per_day distinguishes a correction from a legitimate second cut (FR-10)",
  "Prior assignment_id carried on the replacement"],
 "make check", "FR-8, FR-9, ADR-005"),
"T-035": ("Missing-file alerts", "M4", "T-033", "go/internal/slot/",
 "On deadline expiry with an incomplete slot, emit an alert naming the unmet expectation.",
 ["Alert names the expectation_id and the missing side",
  "Fires once per slot, not per poll",
  "Slot moves to MISSING and stops accepting"],
 "make check", "FR-35"),
"T-036": ("Multi-date split", "M4", "T-027", "python/src/inspector/",
 "A file spanning several value dates splits into per-date sub-batches, each dispatched independently.",
 ["sub_batch_index and sub_batch_total populated",
  "Each sub-batch writes its own Parquet and its own classified message",
  "Row counts across sub-batches sum to the source row count"],
 "make check", "FR-16"),
"T-037": ("Hash-chained audit", "M5", "T-007", "go/internal/audit/",
 "Per-arrival hash chain over decision records, plus a verifier that reports the first break.",
 ["record_hash computed exactly as LLD §2.7 specifies",
  "`make verify-audit` walks every chain and exits non-zero on a break",
  "A deliberately tampered row is detected in a test",
  "Any dispatched instruction reconstructable from the chain alone (FR-39)"],
 "make check && make verify-audit", "03-lld.md §2.7, FR-37"),
"T-038": ("Review queue and four-eyes", "M5", "T-037, T-033", "go/internal/web/, go/internal/slot/",
 "Quarantine queue, decision endpoint, and the review.decisions consumer that releases or rejects an arrival.",
 ["No quarantined arrival dispatches without a recorded human decision (FR-32)",
  "Reviewer identity stamped on the audit record",
  "Corrections can override client, value date or a field mapping",
  "An approved correction is promotable into the client dictionary"],
 "make check", "FR-31, FR-32"),
"T-039": ("Control plane read models and API", "M5", "T-037", "go/cmd/controlplane/, go/internal/web/",
 "Project topics into Postgres read models and serve the LLD §7 API including the SSE stream.",
 ["All eight endpoints implemented per LLD §7",
  "Projection is idempotent under replay",
  "SSE delivers board deltas without polling",
  "Masking applied on the way out"],
 "make check", "03-lld.md §7"),
"T-040": ("UI shell and arrival board", "M6", "T-039", "go/web/",
 "Server-rendered board with bespoke CSS and vendored HTMX. No Node, no CDN, fully offline.",
 ["Board lists arrivals with client, domain, resolved value date, confidence, disposition",
  "Live updates via HTMX SSE swap",
  "Renders correctly with no network access",
  "Visual design is deliberate, not default browser styling"],
 "make up && open the board", "ADR-012"),
"T-041": ("Arrival detail view", "M6", "T-040", "go/web/",
 "Per-arrival page showing the value-date reasoning, the confidence breakdown and every field mapping with its tier and evidence.",
 ["Each mapped field shows source name, canonical name, tier and evidence",
  "Tier is visually distinguishable at a glance",
  "Date disagreement shown prominently when flagged",
  "Account numbers masked, names shown"],
 "make up", "FR-24, ADR-011"),
"T-042": ("Quarantine review and slot board", "M6", "T-040, T-038", "go/web/",
 "Review screen with approve, correct and reject actions, plus a slot board showing open, partial, assigned and missing.",
 ["Reviewer can correct client or value date inline and approve",
  "Action publishes review.decisions and updates the board",
  "Slot board shows the late window remaining per open slot"],
 "make up", "FR-31, FR-42"),
"T-043": ("Corpus generator", "M7", "T-024, T-025", "corpus/, config/",
 "Deterministic generator producing realistic files across six clients, five venues and all six formats.",
 ["Seeded and reproducible; same seed produces identical bytes",
  "Venue-specific column vocabulary per source",
  "Realistic instrument identifiers, currencies and settlement conventions",
  "Includes a matching internal GL extract for each external file"],
 "make seed && make check", "01-requirements.md §8"),
"T-044": ("Adversarial fixtures", "M7", "T-043", "corpus/",
 "The twelve named cases from requirements §8, each an explicit, documented fixture.",
 ["All twelve present and individually named",
  "Each fixture documents what it is designed to break",
  "Includes the late arrival, the date disagreement, the correction, the multi-date file, the four-price record, the bare Price header, the email blob and the unattributable file"],
 "make check", "01-requirements.md §8"),
"T-045": ("Golden and scenario tests", "M7", "T-044, T-032, T-034", "tests/",
 "Snapshot tests per fixture plus one named integration test per adversarial scenario.",
 ["Every fixture has an expected classification and expected Parquet",
  "Twelve named scenario tests, each asserting the specific behaviour",
  "Correctness targets NFR-4, NFR-5, NFR-7 measured and reported",
  "Suite runs offline against the fake adjudicator"],
 "make check && make test-scenarios", "01-requirements.md §8, NFR-4..7"),
"T-046": ("Claude adjudicator", "M8", "T-030", "python/src/inspector/mapping/tier3_llm.py",
 "Implement the live adjudicator behind the frozen interface: structured output, prompt caching, bounded retry, cost counter.",
 ["Returns a mapping validated against the canonical schema before use",
  "Malformed or invalid output falls back to local tiers and marks UNRESOLVED",
  "Prompt cache reuses the client context block across calls",
  "Per-call token and cost counters logged"],
 "make check", "R-2, ADR-004, C-3"),
"T-047": ("Live smoke test", "M8", "T-046, T-045", "tests/live/",
 "Opt-in test hitting the real API, skipped unless ANTHROPIC_API_KEY and HM_LIVE=1 are set.",
 ["Skipped by default; make check never calls the network",
  "Verifies a genuinely novel header set is mapped correctly",
  "Measures the T3 escalation rate against the NFR-8 target of 2 percent"],
 "HM_LIVE=1 make test-live", "NFR-8, C-3"),
"T-048": ("Documentation set", "M9", "T-045", "docs/, README.md",
 "README with the architecture narrative, a runbook, and a rationale document explaining why each significant choice was made.",
 ["README explains the problem before the solution",
  "Every non-obvious tool choice traceable to an ADR",
  "Runbook covers start, seed, demo, verify, teardown and common failures",
  "Diagrams match the code as built, not as designed"],
 "make check", "C-6"),
"T-049": ("Demo walkthrough", "M9", "T-045, T-042", "Makefile, scripts/, docs/",
 "`make demo` drives the adversarial corpus through the running stack in a narrated sequence a viewer can follow on the board.",
 ["Runs in under five minutes end to end",
  "Each adversarial case visibly surfaces on the board as it is handled",
  "Includes the quarantine and review step as a live interaction",
  "Written walkthrough accompanies the command"],
 "make demo", "NFR-11"),
"T-050": ("Ship report", "M9", "T-047, T-048, T-049", "docs/ship-report.md",
 "Evidence of readiness: gate results, coverage, correctness against NFR targets, known issues, rollback posture.",
 ["Every gate in plan §5 shown with its result",
  "NFR-4, NFR-5, NFR-7, NFR-8 reported with measured numbers",
  "Known issues listed honestly, including anything blocked",
  "Go/no-go presented to the user, not asserted"],
 "make check && make demo && make verify-audit", "04-execution-plan.md §5"),
}

TPL = """# {tid} — {title}

**Milestone:** {ms}  **Depends on:** {dep}  **Status:** `pending`

## Scope
Only these paths may be touched: `{scope}`

## Objective
{obj}

## Acceptance criteria
{acc}

## Validation
```
{val}
```

## Reference
{refs} — read only what the criteria above require.

## Handoff notes
_Filled in on completion. Max 10 lines._
"""

def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for tid, (title, ms, dep, scope, obj, acc, val, refs) in T.items():
        slug = title.lower().replace(" ", "-").replace(",", "").replace("/", "-")
        body = TPL.format(tid=tid, title=title, ms=ms, dep=dep, scope=scope, obj=obj,
                          acc="\n".join(f"- [ ] {a}" for a in acc), val=val, refs=refs)
        (OUT / f"{tid}-{slug}.md").write_text(body)
    print(f"wrote {len(T)} task packs to {OUT}")

if __name__ == "__main__":
    main()
